Adding checks for GraphQL Codegen and Breaking Changes to CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,8 +5,73 @@ on:
     branches: [ main ]
 
 jobs:
+  codegen:
+    runs-on: ubuntu-latest
+
+    steps:
+       - uses: actions/checkout@v2
+       - uses: actions/cache@v2
+         with:
+           path: node_modules
+           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
+           restore-keys: |
+             ${{ runner.os }}-npm-
+       - uses: actions/setup-node@v2
+         with:
+           node-version: '14'
+       - name: Install Dependencies
+         run: npm install
+       - name: Run Codegen
+         run: npm run codegen
+       - name: Verify Changed files
+         uses: tj-actions/verify-changed-files@v6.2
+         id: verify-changed-files
+         with:
+           files: |
+            src/utils/resolvers.ts
+       - name: Process changes
+         if: steps.changes.outputs.changed == 1
+         run: |
+          echo "error: Codegen resulted in uncommitted changes"
+          exit 1 
+  
+  releaseSchema:
+    runs-on: ubuntu-latest
+    needs: [codegen]
+    
+    steps:
+       - uses: actions/checkout@v2
+         with:
+           fetch-depth: 0
+       - uses: actions/cache@v2
+         with:
+           path: node_modules
+           key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
+           restore-keys: |
+             ${{ runner.os }}-npm-
+       - uses: actions/setup-node@v2
+         with:
+           node-version: '14'
+       - name: Install Dependencies
+         run: npm install
+       - name: Export Schema
+         run: npm run exportSchema
+       - name: Prepare Schema Release Folder
+         run: |
+          mkdir release
+          cp schema.graphql release/schema.graphql
+       - name: Push to Schema to special Branch
+         uses: s0/git-publish-subdir-action@develop
+         env:
+          REPO: self
+          BRANCH: release
+          FOLDER: release
+          SKIP_EMPTY_COMMITS: true
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          
   lint:
     runs-on: ubuntu-latest
+    needs: [codegen]
 
     steps:
        - uses: actions/checkout@v2
